### ISSUE TITLE
Add wall-e project to pypi

### ISSUE THREAD

**Issue by vishalvvr** [FluffyDietEngine/wall-e#3]

**Comment by vishalvvr** [comment]
New user and project creation is suspended on PyPi
https://status.python.org/incidents/0mld3fml68nd 
Once the service resumes I will create a pypi project for wall-e.

**Comment by FluffyDietEngine** [comment]
Seems like we have to wait till holiday season! 🤷‍♂️

**Comment by vishalvvr** [comment]
Done
https://pypi.org/project/package-sieve
