### ISSUE TITLE
Parameters - bug

### ISSUE THREAD

**Issue by FluffyDietEngine** [FluffyDietEngine/wall-e#6]
If all the parameters are not given, below error is raised. 

```
Traceback (most recent call last):
  File "/home/santhoshsolomon/Projects/optimus-prime/tasks/venv/bin/package-sieve", line 8, in <module>
    sys.exit(main())
  File "/home/santhoshsolomon/Projects/optimus-prime/tasks/venv/lib/python3.10/site-packages/src/wall_e.py", line 118, in main
    modules = traverse_directory(args.project_folder, args.exclude.split(","))
AttributeError: 'NoneType' object has no attribute 'split'
```

Either the error has to be shown gracefully, either the parameters should have default value.

**Comment by vishalvvr** [comment]
> eg: venv, \__pycache__

These are some dirs everyone would exclude, so we can make them default.

**Comment by FluffyDietEngine** [comment]
Can we adapt the pattern of gitignore file as default files/folders to ignore by default?

**Comment by FluffyDietEngine** [comment]
Fixed in https://github.com/FluffyDietEngine/wall-e/releases/tag/v0.2.0
